### ISSUE TITLE
Elm template

### ISSUE THREAD

**Issue by mpizenberg** [Azkellas/a-code-of-ice-and-fire#32]
Hi, not really an issue, just to let you know that I made an Elm template. Elm is a simple functional language that compiles to JavaScript. So even if it is not officially supported by CodinGame, we can use it. Here is the template: https://github.com/mpizenberg/elm-codingame

**Comment by Azkellas** [comment]
Hi,
I added a link to your repo in the starters directory. Thank you for contributing.
